name: vimdoc

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - master

jobs:
  gen_vimdoc:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        # with:
        #   token: ${{ secrets.TRIGGER_WORKFLOW }}

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.11.3

      - name: Generate file
        run: |
          make vimdoc

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "ci(docs): auto generate vimdoc"
